/**
 * AI Service for Frontend-V2 Agent
 * จัดการการเรียกใช้ OpenAI API
 */

import { config } from 'dotenv';
import OpenAI from 'openai';

// Load .env from root
config({ path: '../../../../.env' });

export interface AIGenerationRequest {
  businessCategory: string;
  keywords: string[];
  language: string;
  model?: string;
  temperature?: number;
}

export interface AIGenerationResponse {
  global: {
    palette: {
      primary: string;
      secondary: string;
      bgTone: string;
    };
    tokens: {
      radius: string;
      spacing: string;
    };
  };
  [key: string]: any; // Dynamic block data
}

export class AIService {
  private openai: OpenAI | null = null;
  private isInitialized = false;

  constructor() {
    this.initialize();
  }

  private initialize() {
    try {
      if (process.env.OPENAI_API_KEY) {
        this.openai = new OpenAI({
          apiKey: process.env.OPENAI_API_KEY
        });
        this.isInitialized = true;
        console.log('✅ AI Service initialized with OpenAI');
      } else {
        console.warn('⚠️ No OpenAI API key found, AI Service will use mock data');
        this.isInitialized = false;
      }
    } catch (error) {
      console.error('❌ Failed to initialize AI Service:', error);
      this.isInitialized = false;
    }
  }

  /**
   * Generate content using AI
   */
  async generateContent(request: AIGenerationRequest): Promise<AIGenerationResponse> {
    if (!this.isInitialized || !this.openai) {
      console.log('🔄 AI Service not available, using mock data');
      return this.getMockData(request);
    }

    try {
      console.log('🤖 Generating content with AI...');
      
      const prompt = this.createPrompt(request);
      
      const model = request.model || 'gpt-5-nano';
      const isGpt5 = model.includes('gpt-5');
      
      const response = await this.openai.chat.completions.create({
        model,
        messages: [
          {
            role: 'system',
            content: this.getSystemPrompt()
          },
          {
            role: 'user',
            content: prompt
          }
        ],
        temperature: request.temperature || 1,
        ...(isGpt5 ? { max_completion_tokens: 8000 } : { max_tokens: 8000 })
      });

      const content = response.choices[0]?.message?.content;
      const finishReason = response.choices[0]?.finish_reason;
      
      console.log('🤖 AI Response content:', content);
      console.log('🤖 AI Response choices:', response.choices);
      console.log('🤖 Finish reason:', finishReason);
      console.log('🤖 Usage:', response.usage);
      
      if (!content) {
        console.error('❌ No content in AI response:', {
          choices: response.choices,
          usage: response.usage,
          model: response.model,
          finishReason: finishReason
        });
        
        // Check if it's a length limit issue
        if (finishReason === 'length') {
          console.log('🔄 Response was truncated due to length limit, trying with shorter prompt');
          // Fallback to mock data for now
          return this.getMockData(request);
        }
        
        throw new Error('No content generated by AI');
      }

      return this.parseAIResponse(content, request.businessCategory);
    } catch (error) {
      console.error('❌ AI generation failed:', error);
      console.log('🔄 Falling back to mock data');
      return this.getMockData(request);
    }
  }

  /**
   * Create prompt for AI
   */
  private createPrompt(request: AIGenerationRequest): string {
    const { businessCategory, keywords, language } = request;
    
    return `Generate website content for a ${businessCategory} business.

Keywords: ${keywords.join(', ')}
Language: ${language}

Respond with ONLY valid JSON:

{
  "global": {
    "palette": {
      "primary": "green",
      "secondary": "green", 
      "bgTone": "100"
    },
    "tokens": {
      "radius": "8px",
      "spacing": "1rem"
    }
  },
  "hero-basic": {
    "badge": "Badge text (max 40 chars)",
    "heading": "Main heading", 
    "subheading": "Subheading text",
    "ctaLabel": "Primary CTA",
    "secondaryCta": "Secondary CTA"
  },
  "navbar-basic": {
    "brand": "เจได",
    "brandFirstChar": "จ",
    "ctaButton": "Action button",
    "menuItems": [
      {"label": "Menu item", "href": "/path"}
    ]
  },
  "about-basic": {
    "title": "About title",
    "description": "About description",
    "features": [
      {"title": "คุณสมบัติ 1", "description": "คำอธิบาย"},
      {"title": "คุณสมบัติ 2", "description": "คำอธิบาย"},
      {"title": "คุณสมบัติ 3", "description": "คำอธิบาย"}
    ],
    "stats": [
      {"number": "100+", "label": "ลูกค้า"},
      {"number": "5★", "label": "รีวิว"},
      {"number": "24/7", "label": "บริการ"},
      {"number": "100%", "label": "ความพึงพอใจ"}
    ]
  },
  "contact-basic": {
    "title": "Contact title",
    "subtitle": "Contact subtitle", 
    "address": "Full address",
    "phone": "Phone number",
    "email": "Email address",
    "businessHours": "Business hours"
  },
  "menu-basic": {
    "title": "Menu title",
    "menuItems": [
      {"name": "Item name", "price": "100", "description": "Item description"},
      {"name": "Item name", "price": "150", "description": "Item description"},
      {"name": "Item name", "price": "200", "description": "Item description"},
      {"name": "Item name", "price": "250", "description": "Item description"}
    ]
  },
  "footer-basic": {
    "companyName": "Company name",
    "description": "Company description",
    "socialLinks": [],
    "quickLinks": [],
    "address": "Address",
    "phone": "Phone",
    "email": "Email"
  },
  "theme-basic": {
    "primary": "green",
    "secondary": "green", 
    "bgTone": "100",
    "radius": "8px",
    "spacing": "1rem"
  }
}

Make the content relevant to ${businessCategory} business and use ${language} language.

IMPORTANT: 
- Use only these color names: blue, green, purple, pink, orange, red, yellow, indigo
- Do NOT use hex codes like #FFB300 or #D32F2F
- Keep badge text under 40 characters
- Make badge text short and catchy
- Color selection rules:
  * If keywords mention only ONE color (like "โทนสีเขียว"), use that color for BOTH primary and secondary (same color family)
  * If keywords mention TWO colors (like "ฟ้า เขียว"), use the first color as primary and second as secondary
  * If no specific colors mentioned, choose appropriate colors for the business type
  * For single color requests, use the SAME color for both primary and secondary (e.g., both "green")
  * This creates a cohesive monochromatic color scheme
- Brand name rules:
  * If keywords mention a specific brand name (like "ชื่อ เจได"), extract ONLY the brand name part (e.g., "เจได")
  * Do NOT include words like "ชื่อ" in the brand name
  * Keep the brand name simple and clean as requested
  * Examples: "ชื่อ เจได" → "เจได", "ชื่อ ครัวไทย" → "ครัวไทย"`;
  }

  /**
   * Get system prompt
   */
  private getSystemPrompt(): string {
    return `You are a professional website content generator. 
    Generate high-quality, relevant content for website templates.
    Always respond with valid JSON format ONLY - no markdown, no explanations.
    Use appropriate colors, text, and content for the business category.
    Make content engaging and professional.
    
    CRITICAL RULES:
    - If keywords mention a specific brand name (like "ชื่อ เจได"), extract ONLY the brand name part (e.g., "เจได")
    - Do NOT include words like "ชื่อ" in the brand name
    - Keep brand names simple and clean as requested
    
    IMPORTANT: Your response must be valid JSON that can be parsed directly.`;
  }

  /**
   * Parse AI response
   */
  private parseAIResponse(content: string, businessCategory: string): AIGenerationResponse {
    try {
      // Clean the response (remove markdown if present)
      const cleanContent = content.replace(/```json\n?/g, '').replace(/```\n?/g, '').trim();
      
      const parsed = JSON.parse(cleanContent);
      
      // Validate required fields
      if (!parsed.global || !parsed['hero-basic']) {
        throw new Error('Invalid response structure');
      }
      
      return parsed as AIGenerationResponse;
    } catch (error) {
      console.error('❌ Failed to parse AI response:', error);
      console.log('🔄 Using mock data instead');
      return this.getMockData({ businessCategory, keywords: [], language: 'en' });
    }
  }

  /**
   * Get mock data as fallback
   */
  private getMockData(request: AIGenerationRequest): AIGenerationResponse {
    const { businessCategory } = request;
    
    if (businessCategory === 'restaurant') {
      return {
        global: {
          palette: { primary: 'orange', secondary: 'red', bgTone: '100' },
          tokens: { radius: '8px', spacing: '1rem' }
        },
        'hero-basic': {
          badge: 'ร้านอาหารไทยยอดนิยม',
          heading: 'ลิ้มรสอาหารไทยแท้',
          subheading: 'ประสบการณ์ที่ไม่เหมือนใคร',
          ctaLabel: 'ดูเมนู',
          secondaryCta: 'จองโต๊ะ'
        },
        'navbar-basic': {
          brand: 'ครัวไทย',
          brandFirstChar: 'ค',
          ctaButton: 'สั่งอาหาร',
          menuItems: [
            { label: 'หน้าแรก', href: '/' },
            { label: 'เมนู', href: '/menu' }
          ]
        },
        'about-basic': {
          title: 'เกี่ยวกับเรา',
          description: 'ร้านอาหารไทยแท้',
          features: [
            { title: 'สดใหม่', description: 'ทุกวัน' }
          ],
          stats: [
            { number: '10+', label: 'ปี' }
          ]
        },
        'contact-basic': {
          title: 'ติดต่อเรา',
          subtitle: 'สอบถาม',
          address: '123 ถ.สุขุมวิท',
          phone: '02-123-4567',
          email: 'info@kruathai.com',
          businessHours: 'ทุกวัน 10:00-22:00'
        },
        'menu-basic': {
          title: 'เมนูอาหาร',
          menuItems: [
            { name: 'ข้าวผัดกุ้ง', price: '120', description: 'ข้าวผัดกุ้งสด' },
            { name: 'ผัดไทย', price: '80', description: 'ผัดไทยแท้' },
            { name: 'ต้มยำกุ้ง', price: '150', description: 'ต้มยำกุ้งเผ็ดร้อน' }
          ]
        },
        'footer-basic': {
          companyName: 'ครัวไทย',
          description: 'ร้านอาหารไทย',
          socialLinks: [],
          quickLinks: [],
          address: '123 ถ.สุขุมวิท',
          phone: '02-123-4567',
          email: 'info@kruathai.com'
        },
        'theme-basic': {
          primary: 'orange',
          secondary: 'red',
          bgTone: '100',
          radius: '8px',
          spacing: '1rem'
        }
      };
    }
    
    // Default fallback
    return {
      global: {
        palette: { primary: 'blue', secondary: 'green', bgTone: '100' },
        tokens: { radius: '8px', spacing: '1rem' }
      },
      'hero-basic': {
        badge: 'Default Badge',
        heading: 'Default Heading',
        subheading: 'Default Subheading',
        ctaLabel: 'Learn More',
        secondaryCta: 'Contact Us'
      },
      'navbar-basic': {
        brand: 'Default Brand',
        brandFirstChar: 'D',
        ctaButton: 'Action',
        menuItems: []
      },
      'about-basic': {
        title: 'Default About',
        description: 'Default Description',
        features: [],
        stats: []
      },
      'contact-basic': {
        title: 'Default Contact',
        subtitle: 'Default Subtitle',
        address: 'Default Address',
        phone: 'Default Phone',
        email: 'Default Email',
        businessHours: 'Default Hours'
      },
      'menu-basic': {
        title: 'Default Menu',
        menuItems: [
          { name: 'Default Item', price: '100', description: 'Default description' },
          { name: 'Default Item', price: '150', description: 'Default description' }
        ]
      },
      'footer-basic': {
        companyName: 'Default Company',
        description: 'Default Footer Description',
        socialLinks: [],
        quickLinks: [],
        address: 'Default Address',
        phone: 'Default Phone',
        email: 'Default Email'
      },
      'theme-basic': {
        primary: 'blue',
        secondary: 'green',
        bgTone: '100',
        radius: '8px',
        spacing: '1rem'
      }
    };
  }

  /**
   * Check if AI service is available
   */
  isAvailable(): boolean {
    return this.isInitialized && this.openai !== null;
  }

  /**
   * Get service status
   */
  getStatus() {
    return {
      initialized: this.isInitialized,
      hasApiKey: !!process.env.OPENAI_API_KEY,
      model: process.env.OPENAI_MODEL || 'gpt-5-nano',
      temperature: process.env.OPENAI_TEMPERATURE || '1.0'
    };
  }
}
