'use client';

import React, { useState, useEffect, useMemo } from 'react';
import { Sandpack } from "@codesandbox/sandpack-react";
import { GeneratedFile } from '@/types/sitegen';

interface EnhancedPreviewProps {
  files: GeneratedFile[];
  projectStructure?: {
    name: string;
    description: string;
    features: string[];
  };
}

const EnhancedPreview: React.FC<EnhancedPreviewProps> = ({ files, projectStructure }) => {
  const [isReady, setIsReady] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [device, setDevice] = useState<'desktop' | 'tablet' | 'mobile'>('desktop');

  // แปลง GeneratedFile เป็น Sandpack format
  const sandpackFiles = useMemo(() => {
    try {
      const sandpackFiles: Record<string, string> = {};
      
      files.forEach(file => {
        // จัดการ path ให้ถูกต้อง
        const rawPath = file.path.startsWith('/') ? file.path : `/${file.path}`;
        // ข้ามไฟล์ config ที่ไม่จำเป็นใน runtime ของ Sandpack
        if (/vite\.config\.|next\.config\.|tsconfig\.json|package-lock\.json/.test(rawPath)) {
          return;
        }
        const path = rawPath;
        
        // เพิ่มไฟล์ลงใน Sandpack
        sandpackFiles[path] = file.content;
      });

      // เพิ่มไฟล์ที่จำเป็นสำหรับ Sandpack (React TS template structure at project root)
      if (!sandpackFiles['/package.json']) {
        sandpackFiles['/package.json'] = JSON.stringify({
          name: 'sandpack-react-ts',
          version: '1.0.0',
          dependencies: {
            react: '^18.0.0',
            'react-dom': '^18.0.0'
          }
        }, null, 2);
      }

      // เพิ่ม index.html ที่ราก ถ้าไม่มี
      if (!sandpackFiles['/index.html']) {
        sandpackFiles['/index.html'] = `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${projectStructure?.name || 'Generated Website'}</title>
    <link rel="stylesheet" href="/index.css" />
  </head>
  <body>
    <div id="root"></div>
  </body>
</html>`;
      }

      // เพิ่ม index.tsx ที่ราก ถ้าไม่มี
      if (!sandpackFiles['/index.tsx']) {
        sandpackFiles['/index.tsx'] = `import React from 'react';
import { createRoot } from 'react-dom/client';
import App from './App';
import './index.css';

const root = createRoot(document.getElementById('root')!);
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);`;
      }

      // เพิ่ม App.tsx ที่ราก ถ้าไม่มี
      if (!sandpackFiles['/App.tsx']) {
        sandpackFiles['/App.tsx'] = `import React from 'react';

function App() {
  return (
    <div className="App">
      <h1>Welcome to ${projectStructure?.name || 'Your Website'}</h1>
      <p>${projectStructure?.description || 'A beautiful website generated by AI'}</p>
    </div>
  );
}

export default App;`;
      }

      // เพิ่ม index.css ที่ราก ถ้าไม่มี
      if (!sandpackFiles['/index.css']) {
        sandpackFiles['/index.css'] = `@tailwind base;
@tailwind components;
@tailwind utilities;

body {
  margin: 0;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen',
    'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue',
    sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

.App {
  text-align: center;
  padding: 2rem;
}`;
      }

      setIsReady(true);
      return sandpackFiles;
    } catch (error) {
      console.error('Error preparing Sandpack files:', error);
      setError('Failed to prepare preview files');
      return {};
    }
  }, [files, projectStructure]);

  // Device dimensions
  const deviceDimensions = {
    desktop: { width: '100%', height: '600px' },
    tablet: { width: '768px', height: '600px' },
    mobile: { width: '375px', height: '600px' }
  };

  if (error) {
    return (
      <div className="flex items-center justify-center h-64 bg-red-50 border border-red-200 rounded-lg">
        <div className="text-center">
          <div className="text-red-500 text-lg mb-2">⚠️ Preview Error</div>
          <p className="text-red-600">{error}</p>
        </div>
      </div>
    );
  }

  if (!isReady) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="text-center">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600 mx-auto mb-4"></div>
          <p className="text-gray-600">Preparing preview...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="flex flex-col h-full bg-gray-50">
      {/* Toolbar */}
      <div className="flex items-center justify-between p-4 bg-white border-b border-gray-200">
        <div className="flex items-center space-x-4">
          <h3 className="text-lg font-semibold text-gray-800">Enhanced Preview</h3>
          <span className="px-2 py-1 bg-green-100 text-green-700 text-xs rounded-full">
            ✅ Sandpack Ready
          </span>
        </div>
        
        {/* Device Selector */}
        <div className="flex items-center space-x-2">
          <span className="text-sm text-gray-600 mr-2">Device:</span>
          {(['desktop', 'tablet', 'mobile'] as const).map((deviceType) => (
            <button
              key={deviceType}
              onClick={() => setDevice(deviceType)}
              className={`px-3 py-1 rounded text-sm font-medium transition-colors ${
                device === deviceType
                  ? 'bg-blue-600 text-white'
                  : 'bg-gray-200 text-gray-700 hover:bg-gray-300'
              }`}
            >
              {deviceType.charAt(0).toUpperCase() + deviceType.slice(1)}
            </button>
          ))}
        </div>
      </div>

      {/* Sandpack Preview */}
      <div className="flex-1 p-4 overflow-auto">
        <div 
          className="bg-white rounded-lg shadow-lg overflow-hidden transition-all duration-300 mx-auto"
          style={{ 
            width: deviceDimensions[device].width, 
            maxWidth: '100%',
            height: deviceDimensions[device].height 
          }}
        >
          <Sandpack
            template="react-ts"
            files={sandpackFiles}
            theme="dark"
            customSetup={{
              dependencies: {
                "tailwindcss": "^3.0.0",
                "@tailwindcss/typography": "^0.5.0"
              }
            }}
            options={{
              showNavigator: true,
              showTabs: true,
              showLineNumbers: true,
              showInlineErrors: true,
              wrapContent: true,
              editorHeight: 400,
              autorun: true
            }}
          />
        </div>
      </div>

      {/* File Info */}
      <div className="p-4 bg-white border-t border-gray-200">
        <div className="flex items-center justify-between text-sm text-gray-600">
          <span>📁 {files.length} files generated</span>
          <span>🎯 {projectStructure?.name || 'Generated Website'}</span>
        </div>
      </div>
    </div>
  );
};

export default EnhancedPreview;
