'use client';

import React, { useEffect, useState, useRef } from 'react';
import { GeneratedFile } from '@/types/sitegen';

interface WebsitePreviewProps {
  files: GeneratedFile[];
  projectStructure?: {
    name: string;
    description: string;
    features: string[];
  };
}

const WebsitePreview: React.FC<WebsitePreviewProps> = ({ files, projectStructure }) => {
  const [htmlContent, setHtmlContent] = useState<string>('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [device, setDevice] = useState<'desktop' | 'tablet' | 'mobile'>('desktop');
  const iframeRef = useRef<HTMLIFrameElement>(null);

  // Device dimensions
  const deviceDimensions = {
    desktop: { width: '100%', height: '600px' },
    tablet: { width: '768px', height: '600px' },
    mobile: { width: '375px', height: '600px' }
  };

  // Generate beautiful fallback HTML when no content available
  const generateFallbackHTML = () => {
    const siteName = projectStructure?.name || 'Your Website';
    const siteDescription = projectStructure?.description || 'A beautiful website generated by AI';
    const features = projectStructure?.features || ['Feature 1', 'Feature 2', 'Feature 3'];

    return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${siteName}</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
        body { font-family: 'Inter', sans-serif; }
        .gradient-bg { 
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        }
        .glass-effect {
            backdrop-filter: blur(10px);
            background: rgba(255, 255, 255, 0.1);
            border: 1px solid rgba(255, 255, 255, 0.2);
        }
        .feature-card {
            transition: transform 0.3s ease, box-shadow 0.3s ease;
        }
        .feature-card:hover {
            transform: translateY(-5px);
            box-shadow: 0 20px 25px -5px rgba(0, 0, 0, 0.1);
        }
    </style>
</head>
<body class="bg-gray-50">
    <!-- Navigation -->
    <nav class="bg-white shadow-lg sticky top-0 z-50">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div class="flex justify-between h-16">
                <div class="flex items-center">
                    <div class="text-xl font-bold text-gray-800">${siteName}</div>
                </div>
                <div class="hidden md:flex items-center space-x-8">
                    <a href="#" class="text-gray-600 hover:text-blue-600">Home</a>
                    <a href="#" class="text-gray-600 hover:text-blue-600">About</a>
                    <a href="#" class="text-gray-600 hover:text-blue-600">Services</a>
                    <a href="#" class="text-gray-600 hover:text-blue-600">Contact</a>
                </div>
            </div>
        </div>
    </nav>

    <!-- Hero Section -->
    <section class="gradient-bg min-h-screen flex items-center justify-center text-white relative overflow-hidden">
        <div class="absolute inset-0 bg-black opacity-20"></div>
        <div class="relative z-10 text-center max-w-4xl mx-auto px-4">
            <h1 class="text-5xl md:text-7xl font-bold mb-6 leading-tight">
                Welcome to<br>
                <span class="text-transparent bg-clip-text bg-gradient-to-r from-yellow-400 to-pink-400">
                    ${siteName}
                </span>
            </h1>
            <p class="text-xl md:text-2xl mb-8 opacity-90 leading-relaxed">
                ${siteDescription}
            </p>
            <div class="flex flex-col sm:flex-row gap-4 justify-center">
                <button class="bg-white text-blue-600 px-8 py-4 rounded-lg font-semibold text-lg hover:bg-gray-100 transition-colors">
                    Get Started
                </button>
                <button class="glass-effect text-white px-8 py-4 rounded-lg font-semibold text-lg hover:bg-white hover:bg-opacity-20 transition-all">
                    Learn More
                </button>
            </div>
        </div>
        
        <!-- Floating elements -->
        <div class="absolute top-20 left-10 w-20 h-20 bg-white bg-opacity-10 rounded-full animate-pulse"></div>
        <div class="absolute bottom-20 right-10 w-32 h-32 bg-white bg-opacity-10 rounded-full animate-pulse"></div>
        <div class="absolute top-1/2 left-1/4 w-16 h-16 bg-white bg-opacity-10 rounded-full animate-pulse"></div>
    </section>

    <!-- Features Section -->
    <section class="py-20 bg-white">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div class="text-center mb-16">
                <h2 class="text-4xl font-bold text-gray-900 mb-4">Amazing Features</h2>
                <p class="text-xl text-gray-600 max-w-2xl mx-auto">
                    Discover what makes our platform unique and powerful
                </p>
            </div>
            
            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                ${features.map((feature, index) => `
                    <div class="feature-card bg-white rounded-xl p-8 shadow-lg border border-gray-100">
                        <div class="w-12 h-12 bg-gradient-to-r from-blue-500 to-purple-600 rounded-lg flex items-center justify-center mb-6">
                            <svg class="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z"></path>
                            </svg>
                        </div>
                        <h3 class="text-xl font-semibold text-gray-900 mb-4">${feature}</h3>
                        <p class="text-gray-600 leading-relaxed">
                            This is a detailed description of ${feature.toLowerCase()}, explaining how it benefits your experience and adds value to your workflow.
                        </p>
                    </div>
                `).join('')}
            </div>
        </div>
    </section>

    <!-- Call to Action -->
    <section class="py-20 bg-gradient-to-r from-blue-600 to-purple-700">
        <div class="max-w-4xl mx-auto text-center px-4 sm:px-6 lg:px-8">
            <h2 class="text-4xl font-bold text-white mb-6">Ready to Get Started?</h2>
            <p class="text-xl text-blue-100 mb-8">
                Join thousands of satisfied users who trust our platform
            </p>
            <button class="bg-white text-blue-600 px-10 py-4 rounded-lg font-bold text-lg hover:bg-gray-100 transition-colors shadow-lg">
                Start Your Journey
            </button>
        </div>
    </section>

    <!-- Footer -->
    <footer class="bg-gray-900 text-white py-12">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div class="grid grid-cols-1 md:grid-cols-4 gap-8">
                <div class="col-span-1 md:col-span-2">
                    <h3 class="text-2xl font-bold mb-4">${siteName}</h3>
                    <p class="text-gray-400 leading-relaxed">
                        ${siteDescription}
                    </p>
                </div>
                <div>
                    <h4 class="text-lg font-semibold mb-4">Quick Links</h4>
                    <ul class="space-y-2 text-gray-400">
                        <li><a href="#" class="hover:text-white transition-colors">Home</a></li>
                        <li><a href="#" class="hover:text-white transition-colors">About</a></li>
                        <li><a href="#" class="hover:text-white transition-colors">Services</a></li>
                        <li><a href="#" class="hover:text-white transition-colors">Contact</a></li>
                    </ul>
                </div>
                <div>
                    <h4 class="text-lg font-semibold mb-4">Contact</h4>
                    <ul class="space-y-2 text-gray-400">
                        <li>Email: info@${siteName.toLowerCase().replace(/\s+/g, '')}.com</li>
                        <li>Phone: +1 (555) 123-4567</li>
                        <li>Address: 123 Web Street, Internet City</li>
                    </ul>
                </div>
            </div>
            <div class="border-t border-gray-800 mt-8 pt-8 text-center text-gray-400">
                <p>&copy; 2024 ${siteName}. All rights reserved.</p>
            </div>
        </div>
    </footer>
</body>
</html>`;
  };

  // Simple JSX to HTML conversion for React components
  const convertJSXToHTML = (jsxContent: string): string => {
    try {
      // Extract JSX from return statement
      const jsxMatch = jsxContent.match(/return\s*\(\s*([\s\S]*?)\s*\);?\s*}?\s*$/);
      if (!jsxMatch) return generateFallbackHTML();

      let jsx = jsxMatch[1].trim();
      
      // Basic JSX to HTML conversions
      jsx = jsx
        .replace(/className=/g, 'class=')
        .replace(/htmlFor=/g, 'for=')
        .replace(/\{\/\*[\s\S]*?\*\/\}/g, '') // Remove JSX comments
        .replace(/\{[^}]*\}/g, (match) => {
          // Handle JSX expressions
          if (match.includes('.map(')) return '[Dynamic List]';
          if (match.includes('?')) return 'Conditional Content';
          if (match.includes('useState')) return 'Interactive Element';
          return 'Dynamic Content';
        });

      // Wrap in basic HTML structure if not complete
      if (!jsx.includes('<html')) {
        jsx = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${projectStructure?.name || 'Generated Website'}</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
    ${jsx}
</body>
</html>`;
      }

      return jsx;
    } catch (error) {
      console.error('JSX conversion error:', error);
      return generateFallbackHTML();
    }
  };

  // Generate preview HTML
  useEffect(() => {
    const generatePreview = async () => {
      if (files.length === 0) {
        setHtmlContent(generateFallbackHTML());
        return;
      }
      
      setLoading(true);
      setError(null);

      try {
        console.log('🚀 Generating preview for', files.length, 'files');
        
        // Find main page component
        const mainPage = files.find(f => 
          f.path.includes('page.tsx') || 
          f.path.includes('index.tsx') ||
          f.type === 'page'
        ) || files[0];

        let html = '';

        if (mainPage && mainPage.content.includes('return') && mainPage.content.includes('<')) {
          // Convert React component to HTML
          html = convertJSXToHTML(mainPage.content);
        } else {
          // Use fallback HTML
          html = generateFallbackHTML();
        }

        setHtmlContent(html);
        console.log('✅ Preview generated successfully');
        
      } catch (error) {
        console.error('❌ Preview generation failed:', error);
        setError('Failed to generate preview');
        setHtmlContent(generateFallbackHTML());
      } finally {
        setLoading(false);
      }
    };

    generatePreview();
  }, [files, projectStructure]);

  // Update iframe content
  useEffect(() => {
    if (iframeRef.current && htmlContent) {
      const iframe = iframeRef.current;
      const doc = iframe.contentDocument || iframe.contentWindow?.document;
      if (doc) {
        doc.open();
        doc.write(htmlContent);
        doc.close();
      }
    }
  }, [htmlContent]);

  const dimensions = deviceDimensions[device];

  return (
    <div className="flex flex-col h-full bg-gray-50">
      {/* Toolbar */}
      <div className="flex items-center justify-between p-4 bg-white border-b border-gray-200">
        <div className="flex items-center space-x-4">
          <h3 className="text-lg font-semibold text-gray-800">Website Preview</h3>
          {loading && (
            <div className="flex items-center space-x-2 text-blue-600">
              <svg className="animate-spin h-4 w-4" fill="none" viewBox="0 0 24 24">
                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                <path className="opacity-75" fill="currentColor" d="m4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
              </svg>
              <span className="text-sm">Generating...</span>
            </div>
          )}
        </div>
        
        {/* Device Selector */}
        <div className="flex items-center space-x-2">
          <span className="text-sm text-gray-600 mr-2">Device:</span>
          {(['desktop', 'tablet', 'mobile'] as const).map((deviceType) => (
            <button
              key={deviceType}
              onClick={() => setDevice(deviceType)}
              className={`px-3 py-1 rounded text-sm font-medium transition-colors ${
                device === deviceType
                  ? 'bg-blue-600 text-white'
                  : 'bg-gray-200 text-gray-700 hover:bg-gray-300'
              }`}
            >
              {deviceType.charAt(0).toUpperCase() + deviceType.slice(1)}
            </button>
          ))}
        </div>
      </div>

      {/* Preview Area */}
      <div className="flex-1 p-4 overflow-auto">
        {error ? (
          <div className="flex items-center justify-center h-full">
            <div className="text-center">
              <div className="text-red-500 text-lg mb-2">⚠️ Preview Error</div>
              <p className="text-gray-600">{error}</p>
            </div>
          </div>
        ) : (
          <div className="flex justify-center">
            <div 
              className="bg-white rounded-lg shadow-lg overflow-hidden transition-all duration-300"
              style={{ 
                width: dimensions.width, 
                maxWidth: '100%',
                height: dimensions.height 
              }}
            >
              <iframe
                ref={iframeRef}
                className="w-full h-full border-0"
                title="Website Preview"
                sandbox="allow-scripts allow-same-origin"
              />
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default WebsitePreview;
